### ISSUE TITLE
Open to using a builder pattern?

### ISSUE THREAD

**Issue by ggriffiniii** [dermesser/yup-oauth2#104]
I was thinking there could be an opportunity to improve the way authenticators are created and I was curious to hear if you would be in favor of the concept. To be clear I would plan on implementing the changes, but would like to hear your thoughts before I got started.

To give a rough proposal I believe creating an authenticator with the installed flow could look something like:

```rust
    let mut auth = Authenticator::new(
        InstalledFlow::new()
            .secret(secret)
            .return_method(InstalledFlowReturnMethod::HTTPRedirect),
    )
    .cache_tokens_to_disk("tokenstorage.json")
    .build()
    .expect("authenticator creation failed");
```

In this form the Authenticator would create an owned hyper client and use it for both the authenticator and installed flow. An optional method `with_hyper` would allow the user to provide their own hyper client. DeviceFlow would work similarly. This pattern could also allow removing the ability to create and use InstalledFlow and DeviceFlow without an authenticator, which in my opinion would be a good change to encourage proper use.

Do you feel this would be a welcome change?

**Comment by ggriffiniii** [comment]
I just opened PR #105 which shows what a builder pattern could look like. Could probably use some better documentation, but I think the end result is a little more convenient for users without giving up much flexibility (except where I think the flexibility is more of a footgun than a feature). No pressure, just though it would be nice to have something more concrete to discuss.

**Comment by dermesser** [comment]
Thank you! I've left a comment on there, tl;dr: I like the change, but I'm not convinced if it brings a benefit at this point when the API is maybe not super terse, but still reasonably understandable.

**Comment by dermesser** [comment]
#105 was merged
