### ISSUE TITLE
allow setting grant_type for device code

### ISSUE THREAD

**Issue by ctaggart** [dermesser/yup-oauth2#113]
The `grant_type` for device code authentication using Google is `http://oauth.net/grant_type/device/1.0` https://github.com/dermesser/yup-oauth2/blob/0ab7c4926694a8373d10d468ee012081394cdd10/src/device.rs#L351 [as documented](https://developers.google.com/identity/protocols/OAuth2ForDevices#step-4:-poll-googles-authorization-server). However, the `grant_type` required by Azure for device code flow is `urn:ietf:params:oauth:grant-type:device_code`. https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-device-code

**Comment by dermesser** [comment]
Is this only affecting the device flow?

**Comment by ctaggart** [comment]
Device flow is the only thing I've tried, since that is what I'm trying to integrate into one of our command line apps.

**Comment by ggriffiniii** [comment]
This is done
