### ISSUE TITLE
Sharing ServiceAccountAccess between threads

### ISSUE THREAD

**Issue by alu** [dermesser/yup-oauth2#116]
@dermesser 

We use `ServiceAccountAccess` with `Arc<RwLock<_>>` for share between threads.
But we can't it because `build` method returns `impl GetToken` in 3.1.x later.

There is a workaround?

**Comment by dermesser** [comment]
What is the exact issue? That you cannot use impl objects inside the RwLock? Does Boxing work?

**Comment by alu** [comment]
@dermesser 
Example is below.

```rust
struct Val {
    oauth: std::sync::Arc<std::sync::RwLock<Box<dyn yup_oauth2::GetToken>>>,
}
```

Error message.
```
 --> src/main.rs:3:9
  |
3 |         oauth: std::sync::Arc<std::sync::RwLock<Box<dyn yup_oauth2::GetToken>>>,
  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `yup_oauth2::types::GetToken` cannot be made into an object
  |
  = note: method `token` has generic type parameters
```

Thanks.

**Comment by dermesser** [comment]
I see, this is one of the edge cases for rust I suppose. It seems like I won't come up with a solution to this immediately... is it possible to use a more concrete type instead of GetToken?

**Comment by alu** [comment]
It is not edge case in my mind.
We using this crate for GCS client with web application.
It is generally, right?
Please tell me other solution for the case if there is.

> is it possible to use a more concrete type instead of GetToken?

We can if it was public. Such as `ServiceAccountAccessImpl`.
However, i think it is not cool solution...

So
> I won't come up with a solution to this immediately

Me too :(

**Comment by wgfm** [comment]
We experience the same issue. Since it's not possible to assign the impl GetToken, we work around it by moving the ServiceAccountAccess in a closure. I stripped down our code, so it may need some love to make it work, but here's the gist of it:

```rust
impl SomeType {
    pub fn new(key: ServiceAccountKey) -> Self {
        let client = Client::builder().build(HttpsConnector::new(4));
        let access = ServiceAccountAccess::new(key).hyper_client(client).build();
        let access = Mutex::new(access);

        Self {
            get_token: Box::new(move || {
                let mut access = access.lock().unwrap();
                access.token(vec!["scope1"])
            }),
        }
    }

    fn get_token(&self) -> Box<dyn Future<Item = Token, Error = Error> + Send> {
        Box::new((self.get_token)())
    }
}
```

**Comment by dermesser** [comment]
Unfortunately I haven't come up with a solution to this yet :( Have any of you an idea on how to go about this yet?

**Comment by alu** [comment]
I think this is a natural solution.

1. Change `ServiceAccountAccess` to `Builder`
2. Change `ServiceAccountAccessImpl` to `ServiceAccountAccess`
3. `Builder::build` returns `ServiceAccountAccess`

**Comment by ggriffiniii** [comment]
A major refactor just landed in master that I believe should resolve this. With the refactor service accounts are used very similarly to device and installed flow and via an Authenticator instance. Authenticator is Send+Sync so you should be able to share it between threads. Let me know if this resolves you issue.

**Comment by alu** [comment]
@ggriffiniii
The point of this issue is not by `Sync + Send`.
The point is `GetToken` trait includes generics function (`token()`).

https://doc.rust-lang.org/error-index.html#method-has-generic-type-parameters

**Comment by ggriffiniii** [comment]
I understood the issue with GetToken. The refactor I mentioned removed the GetToken trait because it no longer serves a purpose. I believe it side-steps the issue you're running into and I mentioned that it's Send+Sync since you're wrapping it in a RwLock and that should no longer be required.

**Comment by alu** [comment]
I see! Looking forward to the next version!

Thank you for reply and great crate!
