### ISSUE TITLE
token file with user credentials created world-readable

### ISSUE THREAD

**Issue by davepacheco** [dermesser/yup-oauth2#120]
I'm using this crate via `google-drive3`, which is on `"^1.0"`.  However, it looks to me like the problem described below affects the current version, too.  If not, sorry in advance!

When callers use `DiskTokenStorage` for the first time with a particular path, create an authenticator with it, and then successfully use the authenticator, the tokens are written to a file at the specified path.  The file is created with default permissions, which for many people means that it will be group-readable and world-readable.  That seems like a security issue, since the tokens can be used to make requests as that user via the API (subject to whatever scopes the tokens were created with, of course).

I addressed this in my own program by using `libc::umask` to set the process umask to `0o77`, which removes all group and world permissions.  Admittedly it's annoying to pull in that whole crate and use an unsafe call to do this, and it's especially fraught to modify the umask from a library.  But unless I'm misunderstanding, the default behavior here seems to leave most users somewhat vulnerable.

**Comment by ctaggart** [comment]
This is fixed in the big async pull request. https://github.com/dermesser/yup-oauth2/pull/112#issuecomment-564669892

**Comment by davepacheco** [comment]
Thanks for that pointer!  I didn't find it when I searched for issues but I see it now that I'm searching for PRs, too.

**Comment by ggriffiniii** [comment]
That PR is now merged and a new version of the crate should hopefully be pushed shortly. Going to close this issue for now.
