### ISSUE TITLE
Rust noob unclear how to set OAuth scopes

### ISSUE THREAD

**Issue by DazWilkin** [dermesser/yup-oauth2#121]
Apologies for a stupid noob question. I'm (trying to) learn Rust by doing. I'm familiar with Google's API Client Libraries *but* I'm stumped attempting to revise scopes. IIUC my issues is in understanding how to represent these changes using `yup_oauth2` rather than any particular client library atop it.

+ Q1: How should I correctly specify scopes (for an installed app flow)?
+ Q2: It seems acceptable to be prompted for the bumped (`add_scopes`) but, why doesn't it work?

I reviewed some of the issues in `google-apis-rs` that include ["scopes"](https://github.com/Byron/google-apis-rs/issues?utf8=%E2%9C%93&q=is%3Aissue+scopes), e.g. [#235](https://github.com/Byron/google-apis-rs/issues/235); [#171](https://github.com/Byron/google-apis-rs/issues/171) and these issues are addressed using `add_scope`.

Using Google Fitness API via [`google_fitness1`](https://docs.rs/google-fitness1/1.0.12+20190701/google_fitness1/), I need to use the installed app flow and am mimicking [`drive_example`](https://github.com/dermesser/yup-oauth2/blob/master/examples/drive_example/src/main.rs)

```Rust
let secret = oauth2::read_application_secret(Path::new("./client_secret.json"))
    .expect("client_secret.json");

let client = hyper::Client::with_connector(hyper::net::HttpsConnector::new(
    hyper_rustls::TlsClient::new(),
));

// let storage: oauth2::DiskTokenStorage =
//     DiskTokenStorage::new(&"./token.json".to_string()).unwrap();
let storage: oauth2::MemoryStorage = Default::default();

let authenticator = Authenticator::new(
    &secret,
    DefaultAuthenticatorDelegate,
    client,
    storage,
    Some(FlowType::InstalledInteractive),
);

let client = hyper::Client::with_connector(hyper::net::HttpsConnector::new(
    hyper_rustls::TlsClient::new(),
));

let hub = Fitness::new(client, authenticator);

let data_source_id =
    "derived:com.google.distance.delta:com.google.android.gms:merge_distance_delta";

let resp = hub
    .users()
    .data_sources_get(USER_ID, data_source_id)
    .doit();
```
This generates a prompt that includes `fitness.activity.read` (==`Scope::ActivityRead`):

```
Please direct your browser to https://accounts.google.com/o/oauth2/auth?scope=https://www.googleapis.com/auth/fitness.activity.read&redirect_uri=urn:ietf:wg:oauth:2.0:oob&response_type=code&client_id=[[REDACTED]]
```

Which results **correctly** in:
```
Bad Request (403): Scope not included to read data of type com.google.distance.delta. Possible scopes: https://www.googleapis.com/auth/fitness.location.read, https://www.googleapis.com/auth/fitness.location.write
```
IIUC the call does indeed need `fitness.location.read` (==`Scope::LocationRead`)

I looked at the examples where the authenticator's `token` method is used to apply scopes but was unable to combine this with my code.

I then tried using `add_scope` on the Fitness SDK's `UserDataSourceGetCall`:

```Rust
let resp = hub
    .users()
    .data_sources_get(USER_ID, data_source_id)
    .add_scope(fitness::Scope::LocationRead)
    .doit();
```

but this results in a 2-step authentication flow (I'm asked to open links and paste codes twice) which subsequently fails:
```
Please direct your browser to https://accounts.google.com/o/oauth2/auth?scope=https://www.googleapis.com/auth/fitness.location.read&redirect_uri=urn:ietf:wg:oauth:2.0:oob&response_type=code&client_id=[[REDACTED]]
Success: (Response { status: Ok, headers: Headers { Expires: Mon, 20 Jan 2020 22:15:10 GMT
, Date: Mon, 20 Jan 2020 22:15:10 GMT
...
...
Please direct your browser to https://accounts.google.com/o/oauth2/auth?scope=https://www.googleapis.com/auth/fitness.activity.read&redirect_uri=urn:ietf:wg:oauth:2.0:oob&response_type=code&client_id=[[REDACTED]]
Error: BadRequest(ErrorResponse { error: ServerError { errors: [ServerMessage { domain: "global", reason: "forbidden", message: "Scope not included to read data of type com.google.distance.delta. Possible scopes: https://www.googleapis.com/auth/fitness.location.read, https://www.googleapis.com/auth/fitness.location.write", location_type: None, location: None }], code: 403, message: "Scope not included to read data of type com.google.distance.delta. Possible scopes: https://www.googleapis.com/auth/fitness.location.read, https://www.googleapis.com/auth/fitness.location.write" } })
```

**NB** The first URL includes `fitness.location.read` (as specified in the `add_scopes` function) and the second URL includes the SDK's default `fitness.activity.read`.

Thanks for getting this far!

**Comment by dermesser** [comment]
I believe that yup-oauth2 just gets the scope set, and should do one prompt. Would this maybe fall within the responsibility of google-apis-rs and the issues you linked? I haven't looked much deeper into it, though.

In principle, this would be expected behavior, as the library has to ask for a new token if you request scopes that there is not a token available for yet.

**Comment by DazWilkin** [comment]
Thank you for your reply.

Yes, there's overlap with google-apis-rs.

However, I feel the `authenticator` is where I should be establishing scopes.

In a code sample in this repo, there's an [example](https://github.com/dermesser/yup-oauth2/blob/master/examples/test-installed/src/main.rs) that does:

```rust
    let auth =
        InstalledFlowAuthenticator::builder(app_secret, InstalledFlowReturnMethod::HTTPRedirect)
            .persist_tokens_to_disk("tokencache.json")
            .build()
            .await
            .unwrap();
    let scopes = &["https://www.googleapis.com/auth/drive.file"];

    match auth.token(scopes).await {
        Err(e) => println!("error: {:?}", e),
        Ok(t) => println!("The token is {:?}", t),
    }
```

Even though this is for a different flow, is this the way that I should rewrite my code?

I was hoping that there'd be a way to specify scopes during `Authenticator::new`

**Comment by dermesser** [comment]
Ah I see from where you're coming now. This may be worth taking a look, but in theory the idea was that google-apis-rs knows all about the API, and yup-oauth2 just knows about how to get tokens. If the wrong scopes are specified, it would be google-apis-rs' problem.

But as you've shown, it may make sense to preemptively obtain a token for scopes you know you will want to use. I will take a look later, though unfortunately I don't have a lot of free time for now.

**Comment by dermesser** [comment]
On a second look, having reminded myself how the code looks, what was done in the Drive example you posted should also be possible with your Fit example. Have you tried using the `token()` method of `Authenticator` for this? https://github.com/dermesser/yup-oauth2/blob/master/src/authenticator.rs#L50

**Comment by DazWilkin** [comment]
I tried but ran into problems. I'll try again.

Thank you for your feedback.
