### ISSUE TITLE
Add ability to manually force a token refresh

### ISSUE THREAD

**Issue by ghost** [dermesser/yup-oauth2#125]
Currently there is no way of forcing `Authenticator` to refresh it's access token or even bootstrap the entire tokens from the original credentials.

This means that if server and client disagree about which token is still valid, `yup-oauth2` provides no way to actually get new tokens without fully replacing the entire `Authenticator` in response to a repeated `401` API response for example.

There should be a method on the Authenticator to manually trigger a full refresh.

**Comment by dermesser** [comment]
Does the PR #126 work for your case?

**Comment by ghost** [comment]
Wow, thanks for the incredibly fast response!

Yes, this is exactly what I was looking for!
