### ISSUE TITLE
google_drive3 has no `new` method

### ISSUE THREAD

**Issue by sezna** [dermesser/yup-oauth2#134]
Thanks for making this crate. It is helping drive Rust adoption and has great utility. 

I'm running into an issue running the google drive example:

```
error[E0599]: no function or associated item named `new` found for struct `google_drive3::Drive` in the current scope
  --> src/main.rs:40:22
   |
40 |     let hub = Drive::new(client, authenticator);
   |                      ^^^ function or associated item not found in `google_drive3::Drive`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
error: could not compile `drive_example`.

```

I didn't modify the code in any way, but I did notice this crate is not a member of the workspace so it is presumably not getting tested by your CI.

**Comment by dermesser** [comment]
Apologies for having overlooked this for so long.

**Comment by sezna** [comment]
No worries, thanks!
