### ISSUE TITLE
Google Smart Device Management

### ISSUE THREAD

**Issue by jwinarske** [dermesser/yup-oauth2#149]
Hi,

First thanks for the great work!

I'm looking to use this library with the [Google Smart Device Management API - Get an access token](https://developers.google.com/nest/device-access/authorize).

How do I add a custom code parameter, and redirection url?

Thanks!

**Comment by jwinarske** [comment]
I just added code value to the client json file.  All good now.

**Comment by dermesser** [comment]
Glad you found a solution! Yes, in general the redirect URL is taken from the client secret information. I think usually this is also embedded into it by the developer console.
