### ISSUE TITLE
Predictable ports?

### ISSUE THREAD

**Issue by MTRNord** [dermesser/yup-oauth2#160]
Hi I am trying to run a server where this acts as a lib used to run behind a server. So there is no way to see the console but instead there is one public facing address.

Currently there is a hardcoded random port. Is there a way to ensure it is always the same? That would make it much easier and prevent stuff from constantly breaking.

**Comment by dermesser** [comment]
I see - I believe an earlier version had solved this problem. The easiest way is probably to add an enum value here: https://docs.rs/yup-oauth2/5.1.0/yup_oauth2/enum.InstalledFlowReturnMethod.html

e.g. `HTTPPortRedirect(u16)`, and then thread this through. Would you be willing to file a pull request doing this?

**Comment by luketpeterson** [comment]
Done as you suggested.  I tested that it works as expected.  Thanks.

**Comment by luketpeterson** [comment]
Tested works in released version 8.0.  Thanks for integrating this PR.

**Comment by dermesser** [comment]
Thank you for your contribution!

**Comment by MTRNord** [comment]
While I don't use this crate for a while anymore I still appreciate this being added as a feature :) will help if I ever need to come back to this :)
