### ISSUE TITLE
User impersonation with service accounts

### ISSUE THREAD

**Issue by sheldonjms** [dermesser/yup-oauth2#175]
I am attempting to use a Google Service Account to retrieve mail for users in the organisation.  With the Google Auth Library I can use a method like `setServiceAccountUser` when requesting a token to allow the Service Account to act as another user.  I have been unable to find similar functionality in `yup-oauth2`.   Does similar functionality already exist?

An illustration of the functionality can be found at:

https://github.com/googleapis/google-auth-library-java/blob/f9a9b8ace0199e6b75ed42c7bacfa3be30c34111/oauth2_http/javatests/com/google/auth/oauth2/ServiceAccountCredentialsTest.java

**Comment by sheldonjms** [comment]
[https://developers.google.com/identity/protocols/oauth2/service-account#delegatingauthority](Elsewhere in the Google documentation) it suggests the method `createDelegated` instead.  `yup-oauth2` appears to use the phrase "delegate" for another purpose.

> Delegate domain-wide authority
> If you have delegated domain-wide access to the service account and you want to impersonate a user account, specify the email address of the user account with the createDelegated method of the GoogleCredential object. For example:

```
GoogleCredential credential = GoogleCredential.fromStream(new FileInputStream("MyProject-1234.json"))
    .createScoped(Collections.singleton(SQLAdminScopes.SQLSERVICE_ADMIN))
    .createDelegated("user@example.com");
```

**Comment by sheldonjms** [comment]
It appears I should be able to do 

```rust
let service_authenticator = ServiceAccountAuthenticator::builder(service_account_key.clone())
    .subject("nobody@example.com")
    .build()?;
```
however this always results in a "Lookup failed" response when authenticating with the `imap` crate.

Domain-wide delegation is enabled for the organisation in the Google Admin console.

**Comment by dermesser** [comment]
The `subject` being set is the subject in the JWT. After some cursory research, I've unfortunately not been able to find the right documentation about impersonation (in my memory, Google's documentation used to be a lot better??). If you have a reference, I'd love to take a closer look.

Thank you for being patient with me :grimacing:

**Comment by sheldonjms** [comment]
I created a test application that uses the Google API instead of the OAuth2 API and received a message indicating the service account was not configured correctly.  The difficult here seems to be in error messages not being helpful.  It is unclear how far deep down the stack the core problem with the error message starts.

It does appear the OAuth2 subject is what needs to be set to the address of the impersonated account.

Google's documentation did used to be better. It seems like the current documentation is nothing but circular references and Capitalised Names of Things that have no definition.

I will let you know if I have more information to contribute in the future.  For now I'm on another task.  Thanks for attempting to help.

**Comment by dermesser** [comment]
Thank you for the investigation, I hope we manage to solve this issue at some point!

**Comment by cc8dea2e-4a29-4394-af6d-af0ccc73647a** [comment]
@dermesser @sheldonjms did you manage to solve it?
yup-oauth2 has the ability to use [Domain-wide delegation](https://developers.google.com/identity/protocols/oauth2/service-account#delegatingauthority)?

**Comment by cc8dea2e-4a29-4394-af6d-af0ccc73647a** [comment]
Problem in google-apis-rs crate. Solved here - https://github.com/Byron/google-apis-rs/discussions/487
