### ISSUE TITLE
Accept custom connectors

### ISSUE THREAD

**Issue by kylegentle** [dermesser/yup-oauth2#177]
`Authenticator` currently requires that connectors implement `hyper::client::connect::Connect`, a sealed trait from hyper. This prevents the use of valid connectors that instead implement `tower_service::Service`, [as recommended by hyper](https://docs.rs/hyper/0.13.8/src/hyper/client/connect/mod.rs.html#256-258), and blocks a related issue in google-apis-rs (https://github.com/Byron/google-apis-rs/issues/337).

**Comment by Byron** [comment]
@dermesser The google-API crates will be waiting your feedback before merging the linked PR. I consider you the authority on how this should be implemented and I'd like to not jump the gun like I would usually do :D.

**Comment by dermesser** [comment]
yes, looking at it right now. Very good idea
