### ISSUE TITLE
Service account impersonation

### ISSUE THREAD

**Issue by jneem** [dermesser/yup-oauth2#182]
I have a project that runs in google cloud, with the environment variable GOOGLE_APPLICATION_CREDENTIALS set appropriately. For local development, I don't have permission to generate those service account credentials and so I'd like to use an impersonated token, as described [here](https://cloud.google.com/iam/docs/create-short-lived-credentials-direct).

Is this something that you'd be interested in supporting? If so, I may be able to contribute something.

**Comment by dermesser** [comment]
This definitely sounds interesting! If you find a way to contribute this, I'd be happy to take a PR.

**Comment by jneem** [comment]
This was done in #185
