### ISSUE TITLE
redirect_url to return String not &str

### ISSUE THREAD

**Issue by k-bx** [dermesser/yup-oauth2#204]
I'm trying to implement something like:

```rust
    fn redirect_uri(&self) -> Option<&str> {
        let s: &'static str = &format!(
            "https://mywebsite.comapi/youtube/callback-{}",
            self.port
        );
        Some(s)
    }
```

but I can't, because of lifetimes. I see no good reason to make it return `&str` and not `String`, would be a nice change IMO.

**Comment by ggriffiniii** [comment]
Why not store the url as a member of your struct rather than computing it on each invocation of redirect_uri?

**Comment by k-bx** [comment]
Would I need to make the whole struct be static then? I did make a set of global `&'static str`s that I query but it just seems overcomplicating the code a little.

**Comment by ggriffiniii** [comment]
No, the struct wouldn't need to be static.

`fn redirect_uri(&self) -> Option<&str>` indicates that the `&str` returned needs to live for at least as long as the `&self` reference. The struct would own a `String` that gets created using `format!` on construction and `redirect_uri` would just return `&str` that's a view into that `String`

**Comment by k-bx** [comment]
I see, thanks for explaining!
