### ISSUE TITLE
rustls panics when initializing DefaultConnection

### ISSUE THREAD

**Issue by threema-donat** [dermesser/yup-oauth2#227]
```
thread '<unnamed>' panicked at /rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/rustls-0.23.9/src/crypto/mod.rs:259:14:
no process-level CryptoProvider available -- call CryptoProvider::install_default() before this point
```

with features ["service_account"] enabled. I don't know why this happens since the `ring` feature is enabled both in `rustls` and `hyper-rustls`. Probably related to #224

**Comment by dermesser** [comment]
I was able to reproduce it, can you check if #229 works for you as well? I'm a bit unsure if I selected the right features.

**Comment by threema-donat** [comment]
I'll check it right away! Sorry to not have given you more information, I was quite busy the last days.

**Comment by threema-donat** [comment]
It works for me, but I've created [#231](https://github.com/dermesser/yup-oauth2/pull/231) to avoid unnecessary dependencies. I also have [another MR](https://github.com/dermesser/yup-oauth2/pull/232) in the pipeline to make it configurable if `ring` or `aws-lc-rs` is used.

Thanks a lot for the fast answer and the fix!

**Comment by HollayHorvath** [comment]
Release 11.0 reintroduced this issue
