### ISSUE TITLE
Provide a changelog

### ISSUE THREAD

**Issue by fenhl** [dermesser/yup-oauth2#236]
I am about to upgrade the `yup-oauth2` dependency in my project from version 9 to version 11, so I would like to know what breaking changes there are. The `changelog.md` file only goes up to version 1.0.4, and there are no GitHub releases. Please provide an updated changelog, or if there already is one, add a note to `changelog.md` to make it easier to find.

**Comment by dermesser** [comment]
I suggest you read the very clearly structured output of `git-log(1)`:

```
git log --oneline --graph --decorate
```

Most contributors have left useful commit messages which will tell you what changed.
