### ISSUE TITLE
Feature: Make installed flow wait for the auth code only for a configurable timeout

### ISSUE THREAD

**Issue by dermesser** [dermesser/yup-oauth2#25]
[see this comment](https://github.com/Byron/yup-oauth2/pull/21#discussion_r60830995)

**Comment by ggriffiniii** [comment]
With the async version that just landed any user can wrap a token() call with a tokio::timer::Timeout. Does that satisfy the requirements? The linked comment is no longer available.

**Comment by dermesser** [comment]
I think it refers to this: https://github.com/dermesser/yup-oauth2/pull/21#discussion_r60830995

Wrapping with a timeout does satisfy the problem I had in mind back then.
