### ISSUE TITLE
Fix travis-api-token

### ISSUE THREAD

**Issue by Byron** [dermesser/yup-oauth2#45]
Currently travis (possibly) cannot update the documentation when pushing to master as the secret still refers to [my repository location](https://github.com/dermesser/yup-oauth2/blob/master/.travis.yml#L25).

To fix this, just delete the linked line and execute:

```
cd yup-oauth2
travis encrypt GH_TOKEN=<your github token goes here> --add
```

It seems travis needs to be enabled for this repository as well: https://travis-ci.org/dermesser/yup-oauth2 .

**Comment by dermesser** [comment]
"just" :) this was a nice exercise in yak shaving.

**Comment by dermesser** [comment]
fixed: https://travis-ci.org/dermesser/yup-oauth2/jobs/166219518
