### ISSUE TITLE
About self-hosted documentation

### ISSUE THREAD

**Issue by Byron** [dermesser/yup-oauth2#48]
Hi,

I just noticed that by now, [doc.rs](https://doc.rs) seems to have matured to the point where it is really nice.

As you are publishing to crates.io, it automatically picks up the [crate documentation](https://docs.rs/yup-oauth2/1.0.1/yup_oauth2), and looks quite good doing it.

Adopting it could simplify the `.travis.yml` script for example, and most importantly provide more value to the users.

What are your thoughts on this ?
Thank you

**Comment by dermesser** [comment]
LGTM, I can switch that over soon. Looks like the current setup doesn't really provide anything on top, does it...

**Comment by Byron** [comment]
@dermesser Indeed, the self-hosted docs don't compete with docs.rs at all, which is why it certainly can be abandoned.
