### ISSUE TITLE
Hyper 0.10.0 support (BorrowMut not implemented on hyper::Client)

### ISSUE THREAD

**Issue by skorgu** [dermesser/yup-oauth2#52]
Looks like hyper changed something in 0.10:
```
error[E0277]: the trait bound `hyper::Client: std::borrow::BorrowMut<hyper::client::Client>` is not satisfied
  --> src/main.rs:58:18                                                      
   | 
58 |     let access = oauth2::ServiceAccountAccess::new(client_secret, hyper::Client::new()); 
   |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `std::borrow::BorrowMut<hyper::client::Client>` is not implemented for `hyper::Client`  
   | 
   = note: required by `<oauth2::ServiceAccountAccess<C>>::new`              
```

**Comment by dermesser** [comment]
the upgrade is currently blocked on #51, which depends on Byron/yup-hyper-mock#10. Afterwards I'll try and upgrade.

**Comment by Narfinger** [comment]
Another breaking change with hyper 0.10 is that it doesn't support https anymore. See: https://github.com/hyperium/hyper/commit/2f48612c7e141a9d612d7cb9d524b2f460561f56

Edit: I noticed this seems to be only need to be fixed in the documentation.

**Comment by dermesser** [comment]
tests and main code build and run fine now; do you want to fix the documentation? Otherwise I can do it too.

**Comment by martell** [comment]
With the new hyper 0.11 it seems a https connector was added that uses native-tls.
https://github.com/hyperium/hyper-tls
That essentially gives us back the https support out of the box.
I think the split made a lot of sense for the hyper project.

**Comment by markcatley** [comment]
@Narfinger I had this issue when trying to use yup-oauth2. It would have saved me a bit of effort if the docs were up to dates, so I created a PR. Let me know if I need to change anything, I have tried to follow the contributing guide.
