### ISSUE TITLE
Tracking: Moving from openssl to rustls for signing JWTs (service account authz)

### ISSUE THREAD

**Issue by dermesser** [dermesser/yup-oauth2#56]
I attempted the migration from openssl to rustls (see attached branch below), but there's one small piece missing: Decoding PKCS#8 keyfiles, as delivered by Google Cloud Platform. It already has a feature request: ctz/rustls#43.

Once that is in, there shouldn't be any more obstacles. Fingers crossed.

**Comment by ghost** [comment]
Do I see that correctly and 'all' that is needed is some sort of parser for a file type? Or is it something more involved and 'cryptological' :) ?

**Comment by dermesser** [comment]
I think the parser is the only thing needed, no super cryptologic operations, although the encoding seems quite complex.But I'm ignorant about the details of key formatting and encoding and so on in pkcs#8, and to be honest I don't plan on acquiring that knowledge (shudder) :) It's defined in RFC5958, though -- if you want to take a stab.On Feb 6, 2017 07:43, Sebastian Thiel <notifications@github.com> wrote:Do I see that correctly and 'all' that is needed is some sort of parser for a file type? Or is it something more involved and 'cryptological' :) ?

**Comment by ghost** [comment]
Thanks a lot! Actually I want to take a stab at it, the promise of openssl-free google-apis is too good to pass or wait for :).
