### ISSUE TITLE
1.0.5 in git, but 1.0.7 on crates.io

### ISSUE THREAD

**Issue by emk** [dermesser/yup-oauth2#70]
Hello! I'm trying out `yup-oauth2` and it looks interesting.

I noticed that the latest released version on crates.io was 1.0.7, but the latest on GitHub is 1.0.5. Thank you for building a useful Rust crate!

**Comment by dermesser** [comment]
thanks for creating this issue, I just pushed 1.0.7. Easy to forget :)

**Comment by emk** [comment]
Thank you!
