### ISSUE TITLE
Switch to hyper-tls?

### ISSUE THREAD

**Issue by igor-raits** [dermesser/yup-oauth2#71]
We want to package yup-oauth2 for Fedora, however it depends on rustls which depends on ring and we would like to avoid packaging yet another crypto library. It would be very nice if you could switch to hyper-tls. Or if you don't want to port to hyper 0.12, you could use hyper-native-tls.

**Comment by igor-raits** [comment]
also rustls could be replaced with native-tls

**Comment by dermesser** [comment]
Sounds good -- would you mind sending a patch? I don't have much time these days, so that would greatly accelerate the switch.

**Comment by igor-raits** [comment]
@dermesser let me try. I will write as soon as I have patch or decide that I failed ;)
