### ISSUE TITLE
&String is the worst parameter type.

### ISSUE THREAD

**Issue by IslandUsurper** [dermesser/yup-oauth2#77]
service_account_key_from_file() takes `&String`, but it should probably be `&str` to avoid unnecessary allocations.

Callers can pass a `&String`, and it will auto-ref to `&str`. But I don't think most users will have a String to take a reference in the first place. More likely, they'd follow the example and have a hard-coded file path in a static string slice.

**Comment by Byron** [comment]
As the original author of this crate, I would call it ‘childhood sins’ 😅.
Clearly something that can be improved

**Comment by IslandUsurper** [comment]
No worries. :) Just wanted to make sure I wrote it down and got someone's attention.

**Comment by tylerhawkes** [comment]
I ran into this api issue as well. Taking something generic like `<S: AsRef<str>>(s: S)` would be even better because then you can pass in an owned string or a reference and it just works.
