### ISSUE TITLE
Consider requiring `Send` on `GetToken.token()`s error type to ease use with `Failure`

### ISSUE THREAD

**Issue by cpick** [dermesser/yup-oauth2#85]
The (fantastic!) downstream google* crates are slightly difficult to use with the [failure crate](https://crates.io/crates/failure) ecosystem because their `google_*::Error` types don't automatically implement `failure::Fail` because they are `!Sync` and `!Send` because their `google_*::Error:: MissingToken` variant returns the error from `yup_oauth2::GetToken::token()`: `Box<dyn std::error::Error>`.

If `yup_oauth2::GetToken::token()`s error was also `Send` then `google_*:Error` would implement `failure::Fail` (it still would need to be `Sync`, but that's easily accomplished with the `failure::SyncFailure` helper).

Thanks for this useful set of crates!

**Comment by dermesser** [comment]
is this something you'd be comfortable creating a pull request for? It sounds like you're more familiar with what exactly needs to be done; I don't see a reason not to merge it :)
